ARG PYTHON_VERSION=3.12
ARG NAUTBOT_VERSION=2.4.16

FROM ghcr.io/nautobot/nautobot:${NAUTBOT_VERSION}-py${PYTHON_VERSION}

RUN pip install nautobot-bgp-models==2.3.2 \
    nautobot-secrets-providers[all]==3.2.0 \
    nautobot-golden-config==2.4.1 \
    nautobot-design-builder==2.2.0 \
    nautobot-ssot==3.9.2 \
    nautobot-data-validation-engine==3.2.0 \
    nautobot-firewall-models==2.2.2 \
    nautobot-device-lifecycle-mgmt==3.1.1 \
    nautobot-device-onboarding==4.2.6 \
    nautobot-plugin-nornir==2.2.1 \
    nautobot-dns-models==1.2.0 \
    nautobot-welcome-wizard==2.1.0

# Copy the configuration file into the container
COPY configs/nautobot_config.py /opt/nautobot/nautobot_config.py

USER root

# Copy custom entrypoint script
COPY entry-scripts/docker-entrypoint.sh /docker-entrypoint.sh

# Copy custom secrets loader script
COPY entry-scripts/load-secrets.sh /load-secrets.sh

RUN chmod 755 /docker-entrypoint.sh \
    && chmod 777 /load-secrets.sh

USER nautobot
