---
services:
  nautobot-db-{{ release.name }}:
    image: "{{ values.image.postgres.repository }}:{{ values.image.postgres.tag }}"
    container_name: "nautobot-db-{{ release.name }}"
    environment:
      POSTGRES_DB: "{{ values.config.nautobot_db_name }}"
      POSTGRES_USER: "{{ values.environmental_variable_secrets.nautobot_db_user }}"
      POSTGRES_PASSWORD: "{{ values.environmental_variable_secrets.nautobot_db_password }}"
      PGPASSWORD: "{{ values.environmental_variable_secrets.nautobot_db_password }}"
    command:
      - "-c"
      - "max_connections=1000"
    volumes:
      - "postgres_data_{{ release.name }}:/var/lib/postgresql/data"
    healthcheck:
      test: "pg_isready --username={{ values.environmental_variable_secrets.nautobot_db_user }} --dbname={{ values.config.nautobot_db_name }}"
      interval: "10s"
      timeout: "5s"
      retries: 10
